"""
Django settings for valet_project_app project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECRET_KEY = 'django-insecure-1&j%h4*x4*$ub+3ky8i6l*!di-3so7b9!wyt#mws1=oub$_plb'  # 🚨 INJECT THIS: farrukh commented this
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-1&j%h4*x4*$ub+3ky8i6l*!di-3so7b9!wyt#mws1=oub$_plb')  # 🚨 INJECT THIS: Load from environment variable with a default fallback

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True  # 🚨 INJECT THIS: Commented out hardcoded DEBUG 
DEBUG = os.getenv('DEBUG', 'True') == 'True'  # 🚨 INJECT THIS: Load from environment variable with a default fallback

ALLOWED_HOSTS = ["*"]  # 🚨 INJECT THIS: Allow all hosts for development (change in production)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 🚨 INJECT THIS: Add CORS middleware for handling cross-origin requests
    'api'
]

ROOT_URLCONF = 'valet_project_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'valet_project_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'elite_valet_db'),  # 🚨 INJECT THIS: Load from environment variable with a default fallback
        'USER': os.getenv('DB_USER', 'postgres'),  # 🚨 INJECT THIS: Load from environment variable with a default fallback
        'PASSWORD': os.getenv('DB_PASSWORD', 'admin'),  # 🚨 INJECT THIS: Load from environment variable with a default fallback
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),  # 🚨 INJECT THIS: Load from environment variable with a default fallback
        'PORT': os.getenv('DB_PORT', '5432'),  # 🚨 INJECT THIS: Load from environment variable with a default fallback
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('TIME_ZONE', 'UTC')  # 🚨 INJECT THIS: Load from environment variable with a default fallback

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
